apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    app: blog
spec:
  ports:
  - port: 8080
    name: blog
  clusterIP: None
  selector:
    app: blog
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  serviceName: "blog-service"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: blog
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: blog
        image: lyr8200/blog:v2022.07.01
        ports:
        - containerPort: 8080
          name: blog
        volumeMounts:
        - name: data
          mountPath: /content
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 2Gi